#!/bin/bash
# Template script.  Copy to the name RSYNC${UUID} so we can identify
#  which disk it is copying
# Execute the rsync
#   ./${UUID}.sh source1 target1 source2 target2 source3 target3 ...
#
declare -i donejobs expectedjobs
echo "$@"
ok=1
donejobs=0
expectedjobs=0
firstargument=$1
uuidlogname=$(echo $0 | awk '{n=split($1,a,"/");print "/tmp/"a[n]"copy.log";}')
touch ${uuidlogname}
while [[ ${ok} == 1 ]]
  do
    if [[ "$1" != "" && "$2" != "" ]]
       then
          if [[ ! -d $1 ]]
            then
               shift 2
               continue
            fi
          expectedjobs=$(( expectedjobs + 1 ))
          sudo rsync -av $1 $2 >> ${uuidlogname}
          if [[ $? != 0 ]]
            then
              echo "FAILURE at $1  to $2"
              continue
            else
              donejobs=$(( donejobs + 1 ))
            fi
       else
          echo $1 "..." $2 ",,,"
          ok=0
          continue
       fi
    shift 2
  done
#
/usr/bin/curl -sS -X POST -H Content-Type:application/x-www-form-urlencoded \
http://archivecontrol.wipac.wisc.edu:80/glue/timeset/LastDumpEnded

echo "SUMMARY ${expectedjobs} ${donejobs}"
if [[ "${firstargument}" == "" ]]; then echo "Nothing to do/was done?"; exit 1; fi
cd /opt/i3admin/dumpscripts
source venv/bin/activate
python renamer.py "${firstargument}"
exit 0
