#!/bin/bash
# load_filecatalog
#  Assumes we are running from the jadelta account with the filecatalog
#   environment setup
declare -i fcount
if [[ ! -d "$1" ]]; then echo "$1 is not a directory"; exit 1; fi

echo "load_filecatalog ENTRANCE DEBUG"
cd /home/jadelta/newfilecatalog/file-catalog-indexer

# Setup stuff
eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/setup.sh`
source ./env/bin/activate
# Prepare a blacklist file
blacklistFile=`echo $1 | cksum | awk '{print $1;}'`
# Prepare a temp file of what in the specified ($1) directory is in
# Ric's list.  This is _way_ smaller than Ric's files
tempFile=`echo $1 | md5sum | awk '{print $1;}'`
for efile in `ls /data/user/eevans/data-exp-2020-0*`
  do
    grep "$1" ${efile} >> ${tempFile}
  done
#
for file in $(find "$1" -type f)
  do
      grep "${file}" ${tempFile} > /dev/null
      if [[ $? == 0 ]]; then echo "${file}" >> ${blacklistFile}; fi
  done
skipoption=""
fcount=`wc -l ${blacklistFile} 2>/dev/null | awk '{print $1;}'`
if [[ ${fcount} -gt 0 ]]; then skipoptions="--blacklist-file ${blacklistFile}"; fi
# Run
$SROOT/metaprojects/combo/stable/env-shell.sh `pwd`/indexer.py  -t `cat /home/jadelta/lta/service-token` --site WIPAC $1 --log warning --timeout 150 ${skipoptions}
LASTERROR=$?
rm -f ${blacklistFile} ${tempFile}
exit ${LASTERROR}
